<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!--
        This macro generate two links representing the wheel and differential drive
        gear mechanism and make a joint out of them.
     -->

    <xacro:macro name="swerve_wheel" params="name radius rotater_material spinner_material">

        <xacro:property name="wheel_radius" value="${radius}"/>

        <link name="${name}_rotater_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius * 1.25}" length="${wheel_radius * 1.1}"/>
                </geometry>
                <material name="${rotater_material}"/>
            </visual>

            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius * 1.25}" length="${wheel_radius * 1.1}"/>
                </geometry>
            </collision>

            <xacro:inertial_cylinder mass="${wheel_radius * 3}" length="${wheel_radius * 1.1}" radius="${wheel_radius * 1.25}">
                <origin/>
            </xacro:inertial_cylinder>
        </link>

        <link name="${name}_spinner_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius * 1}" length="${wheel_radius * 1}"/>
                </geometry>
                <material name="${spinner_material}"/>
            </visual>

            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius * 1}" length="${wheel_radius * 1}"/>
                </geometry>
            </collision>

            <xacro:inertial_cylinder mass="${wheel_radius * 5}" length="${wheel_radius * 1}" radius="${wheel_radius * 1}">
                <origin/>
            </xacro:inertial_cylinder>
        </link>

        <joint name="${name}_swerve_joint" type="continuous">
            <origin xyz="0 0 ${wheel_radius * -0.55}" rpy="${pi/2} 0 0"/>
            <parent link="${name}_rotater_link"/>
            <child link="${name}_spinner_link"/>
            <axis xyz="0 0 1"/>
        </joint>

    </xacro:macro>

</robot>