controller_manager:
  ros__parameters:
    update_rate: 200 # The simulator runs on 100Hz (0.01s), this is for timing headroom

    JSB:
      type: joint_state_broadcaster/JointStateBroadcaster

    VEL:
      type: velocity_controllers/JointGroupVelocityController

VEL:
  ros__parameters:
    joints:
      - front_left_wheel_joint
      - front_left_swerve_joint

      - front_right_wheel_joint
      - front_right_swerve_joint

      - rear_left_wheel_joint
      - rear_left_swerve_joint

      - rear_right_wheel_joint
      - rear_right_swerve_joint